  <div class="section">    <div class="container">      <div class="row">        <div class="col s12">          <h3 class="red-text text-darken-3"><img class="service-page-icon" src="img/icons/business-cont.png"> Business Continuity</h3>          <h5>We offer secure, Enterprise-Class Business Continuity without the Enterprise-Class Price.</h5>          <hr>          <div id="overview" class="section scrollspy">            <p class="bold flow-text">Every organization must make business continuity planning part of its business and IT strategy.</p>            <p>Business Continuity encompasses both data availability and disaster recovery, which allows an organization to continue functioning after (and ideally, during) a disaster, rather than simply being able to recover after a disaster. Disasters do not have to be catastrophic, but their results can be. Not having access to email for a day can be as catastrophic as losing the last 25 database transactions; not backing up to an off-site location may be detrimental; and putting all your eggs in one basket – or on one server – is tempting fate. Our new NAS-based technology performs at the block level where the actual digital 1's and 0's are captured from the hard drive, essentially eliminating failures related to open files. Because block-level data is raw information that's independent of file structure formatting, it's the most efficient way to write to a disk.</p>
            <p class="bold flow-text">Restore Server Operations in Less Than 30 Minutes</p>            <p>Now there's a superior backup and disaster recovery solution that matches your business needs – and fits within your budget.</p>
            <p class="bold flow-text">Data Recovery</p>
            <p>
              We partner with Drive Savers to offer damaged HDD data recovery. Learn more by viewing the video or clicking on the link below.
              <script src="http://drivesaversdatarecovery.com/banners/partner-banners.php?banid=1&dsnum=10688" type="text/javascript"></script>
              <br>
              <iframe width="560" height="315" src="https://www.youtube.com/embed/6XA3UWWcFaQ" frameborder="0" allowfullscreen></iframe>
            </p>

            <p class="bold flow-text">Learn more about our backup solutions:</p>            <a href="/backup" class="btn red darken-4">Learn More</a>          </div>          <div class="spacer-50"></div>        </div>      </div>    </div>  </div>
